#!/bin/sh

# install subplugins
echo "submodules initialization"
cd ~/workspace/com.github.hicolour.dot/
git submodule init
git submodule update


# vim
# quick fix for color 
# mkdir ~/workspace/com.github.hicolour.dot/.vim/colors
cp ~/workspace/com.github.hicolour.dot/.vim/bundle/colors/ir_black.vim ~/workspace/com.github.hicolour.dot/.vim/colors/ir_black.vim

# terminal
#
#!/usr/bin/env bash

dir=`dirname $0`

PROFILE=Default

# set palette
gconftool-2 -s -t string /apps/gnome-terminal/profiles/$PROFILE/palette Tango

# set highlighted color to be different from foreground-color
gconftool-2 -s -t bool /apps/gnome-terminal/profiles/$PROFILE/bold_color_same_as_fg false

# set foreground, background and highlight
gconftool-2 \
    --set "/apps/gnome-terminal/profiles/Default/background_color" \
      --type string "#000000"

gconftool-2 \
         --set "/apps/gnome-terminal/profiles/Default/foreground_color" \
            --type string "#606060"


#gconftool-2 -s -t string /apps/gnome-terminal/profiles/$PROFILE/background_color #606060
#gconftool-2 -s -t string /apps/gnome-terminal/profiles/$PROFILE/foreground_color #606060
#gconftool-2 -s -t string /apps/gnome-terminal/profiles/$PROFILE/bold_color `cat $dir/colors/base1`

# make sure the profile is set to not use theme colors
gconftool-2 -s -t bool /apps/gnome-terminal/profiles/$PROFILE/use_theme_colors false


# dot
echo "linking dots.."
cd ~/workspace/com.github.hicolour.dot
DTF=`date +%Y-%m-%d_%H-%M-%S`
DIR=/tmp/.olddot-${DTF}

mkdir ${DIR}
for f in .*;
  do 
    if [ $f = "." ]; then
      echo "."
    elif [ $f = ".." ]; then
      echo ".."
    else 
      echo " processing $f dot";
      mv ~/$f ${DIR}
      ln -s ~/workspace/com.github.hicolour.dot/$f ~/$f
    fi
done

echo "done :)"

